# Actividad 9
# 🔍 Parte 2: Análisis de Datasets
Objetivo: Analizar datasets con Pandas, utilizando filtros y visualización con:
* tablas
* gráficos
* mapas

## Elegí un dataset
* Realizar exploración básica

*  ### Avistajes de felinos en Argentina
    * Link para descarga: https://archivos.linti.unlp.edu.ar/index.php/s/5iC9FrYWiGi11d0
    * Nombre del archivo: felinos_filtrado.csv
    * Descargado y adaptado de: https://www.gbif.org/
    * Descripción: describe los avistajes de felinos en peligro de extinción con ubicación, especie, fecha etc.
* ### Áreas protegidas
    * Link para descarga: https://archivos.linti.unlp.edu.ar/index.php/s/Eqw1eAVC1pdefmb
    * Descargado de: https://dnsg.ign.gob.ar/apps/api/v1/capas-sig/Geodesia+y+demarcaci%C3%B3n/L%C3%ADmites/area_protegida/csv*
    * Página consultada: https://www.ign.gob.ar/NuestrasActividades/InformacionGeoespacial/CapasSIG
    * Descripción: detalle de las áreas protegidas terrestres y marítimas
    * Documento con detalle de los datos: https://archivos.linti.unlp.edu.ar/index.php/s/9LoXcqzxI8bDzbN
* ### Aeropuertos Argentina
    * Link para  descarga: https://archivos.linti.unlp.edu.ar/index.php/s/TYVZ5U6HC457M1k
    * Nombre del archivo: ar-airports.csv
    * Descargado de: https://ourairports.com/countries/AR/airports.csv
    * Descripción: Aeropuertos de Argentina por tipo y localidad
* ### Conectividad Argentina
    * Link para descarga: https://archivos.linti.unlp.edu.ar/index.php/s/3k2TO5sSzaAU6IY
    * Nombre del archivo: Conectividad_Internet.csv
    * Descargado de : https://datos.gob.ar/dataset/enacom-conectividad-al-servicio-internet/archivo/enacom_CONEC-AL-SERVI-DE-INTER_0
    * Descripción: Describe las tecnologías disponibles en las localidades para acceder al servicio de Internet fijo y móvil
* ### Precios combustibles
    * [Link para descarga](https://archivos.linti.unlp.edu.ar/index.php/s/x0InilFLhgt1B1R).
    * Descargado de: https://www.datos.gob.ar/dataset/energia-precios-surtidor---resolucion-3142016
    * Descripción: Datos del Sistema en línea de información de precios de combustibles en surtidor, a través del cual los titulares de bocas de expendio de combustibles líquidos inscriptos en el registro creado por la resolución n° 1.102/2004 presentan la información relativa a precios de comercialización minorista dentro de las 8 (ocho) horas de producida una modificación en el precio en surtidor.
* ### Ferrocarriles.
    *  [Link para descarga](https://archivos.linti.unlp.edu.ar/index.php/s/Pr6vcKL9fxfmZoj)
    * Descargado de :https://datos.transporte.gob.ar/dataset/cruces-ferroviarios
    * Descripción: Cruces ferroviarios con respecto a la red vial nacional. Relevados por la Dirección Nacional de Vialidad. Año 2016.

In [ ]:
Duarte ALejo eligió Aeropuertos

In [ ]:
import pandas as pd
import plotly.express as pl
import folium as fo

aeropuertos=pd.read_csv("ar-airports.csv")

# ✅ Etapa 1: Exploración Básica (10 min)
* Cantidad de filas y columans
* Nombres de las columnas
* Tipos de datos de las columnas
* Ver las primeras 10 filas del dataset

In [ ]:
CantFilCol = list(aeropuertos.shape)

print("Este dataset tiene", CantFilCol[0], "Filas y", CantFilCol[1], "Columnas")
print("Sus nombres y tipo son", aeropuertos.dtypes)
print("Sus primeras 10 filas son: ")
aeropuertos.head(10)

Este dataset tiene 956 Filas y 24 Columnas
Sus nombres y tipo son id                     int64
ident                 object
type                  object
name                  object
latitude_deg         float64
longitude_deg        float64
elevation_ft         float64
continent             object
country_name          object
iso_country           object
region_name           object
iso_region            object
local_region          object
municipality          object
scheduled_service      int64
gps_code              object
icao_code             object
iata_code             object
local_code            object
home_link             object
wikipedia_link        object
keywords              object
score                  int64
last_updated          object
dtype: object
Sus primeras 10 filas son:

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,country_name,iso_country,...,scheduled_service,gps_code,icao_code,iata_code,local_code,home_link,wikipedia_link,keywords,score,last_updated
0,5781,SAEZ,large_airport,Minister Pistarini International Airport,-34.822200,-58.535800,67.0,SA,Argentina,AR,...,1,SAEZ,SAEZ,EZE,EZE,http://www.aa2000.com.ar/index.php,https://en.wikipedia.org/wiki/Ministro_Pistari...,"BUE, Ezeiza",1275,2022-10-27T15:05:29+00:00
1,5771,SABE,large_airport,Jorge Newbery Airpark,-34.559200,-58.415600,18.0,SA,Argentina,AR,...,1,SABE,SABE,AEP,AER,NaN,https://en.wikipedia.org/wiki/Aeroparque_Jorge...,NaN,1050,2021-10-07T15:55:36+00:00
2,5835,SAWH,medium_airport,Ushuaia - Malvinas Argentinas International Ai...,-54.843300,-68.295800,102.0,SA,Argentina,AR,...,1,SAWH,SAWH,USH,USU,NaN,https://en.wikipedia.org/wiki/Ushuaia_%E2%80%9...,NaN,750,2025-03-22T20:48:42+00:00
3,5806,SARI,medium_airport,Cataratas Del Iguazú International Airport,-25.737301,-54.473400,916.0,SA,Argentina,AR,...,1,SARI,SARI,IGR,IGU,http://www.aa2000.com.ar/iguazu,https://en.wikipedia.org/wiki/Cataratas_del_Ig...,Iguaçu,750,2018-09-13T12:34:47+00:00
4,5831,SAWC,medium_airport,El Calafate - Commander Armando Tola Internati...,-50.280300,-72.053101,669.0,SA,Argentina,AR,...,1,SAWC,NaN,FTE,ECA,http://www.aeropuertoelcalafate.com/en/,https://en.wikipedia.org/wiki/Comandante_Arman...,NaN,500,2022-01-12T18:23:15+00:00
5,5786,SAME,medium_airport,El Plumerillo Airport,-32.831699,-68.792900,2310.0,SA,Argentina,AR,...,1,SAME,SAME,MDZ,DOZ,NaN,https://en.wikipedia.org/wiki/Governor_Francis...,NaN,750,2011-02-17T01:49:01+00:00
6,5852,SAZS,medium_airport,San Carlos de Bariloche Airport,-41.151199,-71.157501,2774.0,SA,Argentina,AR,...,1,SAZS,SAZS,BRC,BAR,http://www.aa2000.com.ar/bariloche,https://en.wikipedia.org/wiki/San_Carlos_de_Ba...,Teniente Luis Candelaria,750,2025-03-09T01:30:49+00:00
7,5811,SASA,medium_airport,Martin Miguel De Guemes International Airport,-24.856001,-65.486198,4088.0,SA,Argentina,AR,...,1,SASA,SASA,SLA,SAL,NaN,https://en.wikipedia.org/wiki/Mart%C3%ADn_Migu...,NaN,750,2011-07-03T00:07:47+00:00
8,5773,SACO,medium_airport,Ingeniero Ambrosio Taravella Airport,-31.323601,-64.208000,1604.0,SA,Argentina,AR,...,1,SACO,SACO,COR,CBA,NaN,https://en.wikipedia.org/wiki/Ingeniero_Ambros...,NaN,750,2019-04-15T20:31:25+00:00
9,37,AR-0742,closed,Colonia Catriel Airport,-37.910198,-67.834999,1026.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,NaN,NaN,https://en.wikipedia.org/wiki/Colonia_Catriel_...,"SA30, SA0U, SA30, CCT, CLT",50,2025-02-25T14:37:41+00:00

# ✅ Etapa 2: Análisis por temática(10 min)
* Cada dataset se analizará según categorías correspondiente a los datos que lo conforman

In [ ]:
print(aeropuertos['type'].unique())
print(aeropuertos['type'].value_counts())
print(aeropuertos['local_code'].value_counts())

['large_airport' 'medium_airport' 'closed' 'small_airport' 'heliport'
 'balloonport']
type
small_airport     694
heliport          148
medium_airport     69
closed             42
large_airport       2
balloonport         1
Name: count, dtype: int64
local_code
HSN    2
ROH    2
RAW    1
RLC    1
RES    1
      ..
BOG    1
ACB    1
EML    1
DOR    1
TIR    1
Name: count, Length: 769, dtype: int64

# ✅ Etapa 3: Filtrar y Limpiar Datos (15 min)

# ✅ Etapa 4: Valores Nulos y Estadísticas (10 min)
* Mostrar la composición de las columnas indicando aquellas con datos faltantes

In [ ]:
aeropuertos.describe()
aeropuertos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 956 entries, 0 to 955
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 956 non-null    int64
 1   ident              956 non-null    object
 2   type               956 non-null    object
 3   name               956 non-null    object
 4   latitude_deg       956 non-null    float64
 5   longitude_deg      956 non-null    float64
 6   elevation_ft       923 non-null    float64
 7   continent          956 non-null    object
 8   country_name       956 non-null    object
 9   iso_country        956 non-null    object
 10  region_name        956 non-null    object
 11  iso_region         956 non-null    object
 12  local_region       956 non-null    object
 13  municipality       941 non-null    object
 14  scheduled_service  956 non-null    int64
 15  gps_code           228 non-null    object
 16  icao_code          93 non-null     object
 17  iata_code          103 non-null    object
 18  local_code         771 non-null    object
 19  home_link          14 non-null     object
 20  wikipedia_link     186 non-null    object
 21  keywords           119 non-null    object
 22  score              956 non-null    int64
 23  last_updated       956 non-null    object
dtypes: float64(3), int64(3), object(18)
memory usage: 179.4+ KB

# ✅ Etapa 5: Visualización con Mapas (15 min)

*  ### Avistajes de felinos en Argentina
    * **Mapa**: mostrar iconos de color según el tipo de "genus" .
* ### Áreas protegidas
    * **Mapa**: mostrar iconos de color según el tipo de área protegida definida en la columna "tap" que indica (Parque, Reserva, MonumentosNatural).
* ### Aeropuertos Argentina
    * **Mapa**: mostrar iconos de color según el tipo de aeropuerto: type
* ### Conectividad Argentina
    * **Mapa**: mostrar las localidades donde hay FIBRAOPTICA.
* ### Precios combustibles
    *  **Mapa**: mostrar los registros de las provincias de la Patagonia según "tipohorario".
* ### Ferrocarriles.
    * **Mapa**: mostrar las estaciones en el mapa según el tipo indicado en la columna "gna".

## 📌 Paso 1.Generar un mapa **base** para luego agregar los puntos

In [ ]:
def genMap():
    attr = (
        '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> '
        'contributors, &copy; <a href="https://cartodb.com/attributions">CartoDB</a>'
    )

    tiles = 'https://wms.ign.gob.ar/geoserver/gwc/service/tms/1.0.0/capabaseargenmap@EPSG%3A3857@png/{z}/{x}/{-y}.png'
    m = fo.Map(
        location=(-33.457606, -65.346857),
        control_scale=True,
        zoom_start=5,
        name='es',
        tiles=tiles,
        attr=attr
    )
    return m

In [ ]:
mapa=genMap()

## 📌 Paso 2. Definir la función para  agregar los puntos

In [ ]:
def agregarMark(row):
    colores = {'small_airport': 'red', 'medium_airport': 'yellow', 'large_airport': 'green', 'heliport' : 'blue'}
    color = colores.get(row['type'], 'gray')
    fo.CircleMarker(
        location=[row['latitude_deg'], row['longitude_deg']],
        radius=6,
        color=color,
        fill=True,
        popup=row['name']
        ).add_to(mapa)

## 📌 Paso 3. Agrergar los puntos al mapa

In [ ]:
aeropuertos.apply(agregarMark, axis=1)
mapa

In [ ]:
print("Puertos y Aeropuertos de Santa Cruz:")
aeropuertos[aeropuertos["region_name"]=="Santa Cruz Province"]

Aeropuertos de Santa Cruz:

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,country_name,iso_country,...,scheduled_service,gps_code,icao_code,iata_code,local_code,home_link,wikipedia_link,keywords,score,last_updated
4,5831,SAWC,medium_airport,El Calafate - Commander Armando Tola Internati...,-50.280300,-72.053101,669.0,SA,Argentina,AR,...,1,SAWC,NaN,FTE,ECA,http://www.aeropuertoelcalafate.com/en/,https://en.wikipedia.org/wiki/Comandante_Arman...,NaN,500,2022-01-12T18:23:15+00:00
10,5834,SAWG,medium_airport,Piloto Civil N. Fernández Airport,-51.608900,-69.312600,61.0,SA,Argentina,AR,...,1,SAWG,SAWG,RGL,GAL,NaN,https://en.wikipedia.org/wiki/Piloto_Civil_Nor...,Brigadier General D. A. Parodi,750,2011-02-13T13:44:01+00:00
16,5836,SAWJ,medium_airport,Capitan D Daniel Vazquez Airport,-49.306816,-67.802596,203.0,SA,Argentina,AR,...,0,SAWJ,SAWJ,ULA,SJU,NaN,https://en.wikipedia.org/wiki/Capit%C3%A1n_Jos...,NaN,750,2025-02-05T15:21:04+00:00
33,5832,SAWD,medium_airport,Puerto Deseado Airport,-47.735300,-65.904100,268.0,SA,Argentina,AR,...,1,SAWD,SAWD,PUD,ADO,NaN,https://en.wikipedia.org/wiki/Puerto_Deseado_A...,NaN,750,2023-05-01T17:23:28+00:00
34,5839,SAWU,medium_airport,Santa Cruz Airport,-50.016500,-68.579200,364.0,SA,Argentina,AR,...,0,SAWU,SAWU,RZA,SCZ,NaN,https://en.wikipedia.org/wiki/Santa_Cruz_Airpo...,NaN,750,2025-02-05T15:20:33+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899,42898,AR-0476,heliport,Heliplataforma Equipo Modular M-10 Heliport,-52.548900,-68.311900,108.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,HEM,NaN,NaN,NaN,0,2009-10-20T11:13:21+00:00
901,42896,AR-0474,heliport,Heliplataforma Barcaza Yagana Heliport,-52.522500,-68.280600,49.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,HBY,NaN,NaN,NaN,0,2009-10-20T11:13:21+00:00
903,42897,AR-0475,heliport,Heliplataforma Buque Skandi Patagonia Heliport,-52.000000,-67.000000,NaN,SA,Argentina,AR,...,0,NaN,NaN,NaN,HSP,NaN,NaN,NaN,0,2009-10-20T11:13:21+00:00
911,340028,AR-0665,heliport,Heliplataforma Móvil Ocean Scepter,-46.466667,-67.433333,505.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,HOS,NaN,NaN,NaN,0,2021-01-22T10:22:35+00:00
934,348452,AR-0686,closed,Río Gallegos Air Base,-51.648610,-69.203140,56.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2021-10-07T12:06:42+00:00

In [ ]:
aeropuertos['region_name'].value_counts()
aedeco=aeropuertos[aeropuertos["region_name"] == "Córdoba Province"]
aedeco

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,country_name,iso_country,...,scheduled_service,gps_code,icao_code,iata_code,local_code,home_link,wikipedia_link,keywords,score,last_updated
8,5773,SACO,medium_airport,Ingeniero Ambrosio Taravella Airport,-31.323601,-64.208000,1604.0,SA,Argentina,AR,...,1,SACO,SACO,COR,CBA,NaN,https://en.wikipedia.org/wiki/Ingeniero_Ambros...,NaN,750,2019-04-15T20:31:25+00:00
43,29806,SACD,small_airport,Coronel Olmedo Airport,-31.487499,-64.141403,1416.0,SA,Argentina,AR,...,0,SACD,NaN,NaN,EDO,NaN,https://en.wikipedia.org/wiki/Coronel_Olmedo_A...,NaN,50,2024-05-18T21:35:09+00:00
58,17,SA05,small_airport,Bell Ville Airport,-32.659900,-62.702000,429.0,SA,Argentina,AR,...,0,SA05,NaN,NaN,BEL,NaN,NaN,SA05,50,2009-10-20T11:12:52+00:00
61,29803,SACE,small_airport,Escuela de Aviación Militar (Military Aviation...,-31.444223,-64.283377,1646.0,SA,Argentina,AR,...,0,SACE,NaN,NaN,ESC,NaN,https://en.wikipedia.org/wiki/Escuela_de_Aviac...,NaN,50,2024-05-18T21:35:29+00:00
78,5796,SAOC,medium_airport,Area De Material Airport,-33.085098,-64.261299,1380.0,SA,Argentina,AR,...,0,SAOC,SAOC,RCU,TRC,NaN,https://en.wikipedia.org/wiki/Las_Higueras_Air...,NaN,375,2024-05-19T23:13:19+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892,38958,AR-0283,heliport,Norberto Cordeiro Heliport,-31.414200,-64.496900,2036.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,HAI,NaN,NaN,NaN,25,2009-10-20T11:13:17+00:00
908,42889,AR-0467,heliport,Berrini Heliport,-31.439700,-64.343300,1811.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,HBR,NaN,NaN,NaN,0,2009-10-20T11:13:21+00:00
909,318510,AR-0572,heliport,Centro Cívico Bicentenario Heliport,-31.420370,-64.173235,1306.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,HBI,NaN,NaN,NaN,0,2016-06-11T23:48:41+00:00
952,42893,AR-0471,heliport,Dayry Partners Americas Manufacturing Argentin...,-32.440000,-63.228900,639.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,HNE,NaN,NaN,NaN,0,2009-10-20T11:13:21+00:00
954,42903,AR-0481,heliport,Roca Heliport,-32.060000,-64.779400,3444.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,HYC,NaN,NaN,NaN,0,2009-10-20T11:13:21+00:00

In [ ]:
aedesa=aeropuertos[aeropuertos["region_name"] == "Salta Province"]
aedesa

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,country_name,iso_country,...,scheduled_service,gps_code,icao_code,iata_code,local_code,home_link,wikipedia_link,keywords,score,last_updated
7,5811,SASA,medium_airport,Martin Miguel De Guemes International Airport,-24.856001,-65.486198,4088.0,SA,Argentina,AR,...,1,SASA,SASA,SLA,SAL,NaN,https://en.wikipedia.org/wiki/Mart%C3%ADn_Migu...,NaN,750,2011-07-03T00:07:47+00:00
51,5815,SAST,medium_airport,General Enrique Mosconi Airport,-22.616877,-63.793015,1472.0,SA,Argentina,AR,...,0,SAST,SAST,TTG,TAR,NaN,https://en.wikipedia.org/wiki/Tartagal_Airport,NaN,750,2025-02-20T01:01:25+00:00
138,30,SA22,small_airport,Santa Victoria Airport,-22.285700,-62.713699,918.0,SA,Argentina,AR,...,0,SA22,NaN,NaN,VIT,NaN,NaN,SA22,50,2011-07-10T05:36:12+00:00
164,5813,SASO,medium_airport,Orán Airport,-23.152800,-64.329201,1171.0,SA,Argentina,AR,...,0,SASO,SASO,ORA,ORA,NaN,https://en.wikipedia.org/wiki/Or%C3%A1n_Airport,NaN,250,2024-05-16T20:11:54+00:00
183,42841,AR-0419,small_airport,Finca La Frontera Airport,-22.123510,-63.290550,160.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,SMF,NaN,NaN,NaN,50,2016-06-05T11:01:51+00:00
218,318241,AR-0514,small_airport,Finca Cuchuy Airport,-23.040000,-63.721100,928.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,FCU,NaN,NaN,NaN,50,2016-06-03T12:21:46+00:00
236,13,SA01,small_airport,Cachi Airport,-25.105000,-66.157204,8232.0,SA,Argentina,AR,...,0,SA01,NaN,NaN,CCS,NaN,NaN,SA01,50,2011-07-10T01:05:22+00:00
237,14,SA02,small_airport,Cafayate Airport,-26.056101,-65.936897,5375.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,CAF,NaN,https://es.wikipedia.org/wiki/Aer%C3%B3dromo_G...,"SA02, Gilberto Lavaque",50,2024-03-12T17:07:51+00:00
362,318253,AR-0525,small_airport,Salvita Airport,-23.212800,-64.033900,928.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,SLV,NaN,NaN,NaN,50,2016-06-03T18:01:21+00:00
390,318254,AR-0526,small_airport,El Desafio,-23.242600,-63.323000,800.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,FDD,NaN,NaN,NaN,50,2016-06-03T19:02:22+00:00
405,42846,AR-0424,small_airport,General Belgrano Airport,-24.745834,-65.418892,4136.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,GBL,http://www.aeroclubsalta.com/,NaN,SA74,50,2017-01-08T14:21:23+00:00
408,553521,AR-0738,small_airport,Ingenio San Isidro airstrip,-24.684730,-65.017047,695.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,NaN,NaN,NaN,"Ingenio, San, Isidro, Airstrip, Pista,",50,2024-10-22T02:41:39+00:00
412,318255,AR-0527,small_airport,Finca La Hercilia Airport,-22.614700,-63.662759,1227.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,FLH,NaN,NaN,NaN,50,2016-06-03T22:13:30+00:00
472,38887,AR-0212,small_airport,Agropecuaria Rio Juramento Airport,-25.186701,-64.082802,1184.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,JGA,NaN,NaN,NaN,50,2011-07-09T12:24:56+00:00
509,318265,AR-0534,small_airport,AeroSoluciones Airport,-24.748890,-64.235000,1614.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,LLA,NaN,NaN,NaN,50,2016-06-04T08:42:46+00:00
559,38948,AR-0273,small_airport,Metán Airport,-25.514400,-64.965599,2765.0,SA,Argentina,AR,...,0,SASM,NaN,NaN,MTN,NaN,NaN,NaN,50,2011-02-11T21:43:52+00:00
585,318271,AR-0539,small_airport,Finca Toloche Airport,-25.434600,-63.857800,1040.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,NST,NaN,NaN,NaN,50,2016-06-04T11:21:35+00:00
601,327644,AR-0640,small_airport,Pichanal-Franzini Airport,-23.338946,-64.247126,1004.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,2105,NaN,NaN,NaN,50,2018-05-06T14:34:20+00:00
608,318276,AR-0543,small_airport,SAS Aeroaplicaciones Airport,-24.806670,-64.181110,1498.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,PCA,NaN,NaN,NaN,50,2016-06-04T13:23:02+00:00
609,327621,AR-0634,small_airport,Finca Porvenir 8 Airport,-24.994562,-64.341664,1732.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,2800,NaN,NaN,NaN,50,2018-05-05T15:36:39+00:00
663,41545,SASR,small_airport,Rivadavia Airport,-24.188601,-62.883400,679.0,SA,Argentina,AR,...,0,SASR,NaN,NaN,RIV,NaN,NaN,NaN,50,2011-07-03T00:24:03+00:00
672,38995,AR-0320,small_airport,Rosario De La Frontera Airport,-25.828056,-64.968056,2746.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,FRO,NaN,NaN,NaN,50,2011-07-14T01:38:43+00:00
872,38768,AR-0093,heliport,Centro Cívico Grand Bourg Heliport,-24.780600,-65.451400,4132.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,HGB,NaN,NaN,NaN,25,2009-10-20T11:13:15+00:00
873,38834,AR-0159,heliport,Finca Las Costas Heliport,-24.770300,-65.495600,4300.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,HFC,NaN,NaN,NaN,25,2009-10-20T11:13:17+00:00
874,38869,AR-0194,heliport,Hospital De Milagro Heliport,-24.773100,-65.415600,4068.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,HHM,NaN,NaN,NaN,25,2009-10-20T11:13:17+00:00
940,560398,AR-0740,heliport,Temet Helipad,-24.836242,-65.372347,3871.0,SA,Argentina,AR,...,0,NaN,NaN,NaN,HTE,NaN,NaN,NaN,0,2024-11-26T12:30:54+00:00